### ISSUE TITLE
CFBundleIdentifier is always 'io.nwjs.nwjs'

### ISSUE THREAD

**Issue by brinsche-fkt42** [charlielee/nwjs-packager#19]
I noticed that the CFBundleIdentifier in the built .app is always
````
<key>CFBundleIdentifier</key>
<string>io.nwjs.nwjs</string>
````
I assume this could cause problems because https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier says it should be a unique identifier.

How much work would it be to allow customising the field? Maybe a new `appMacBundleIdentifier` and using that wherever the Info.plists are modified would be enough?

**Comment by charlielee** [comment]
Thanks for raising this issue. It should be straightforward to add this feature as we already change all the Info.plist files in https://github.com/charlielee/nwjs-packager/blob/master/bin/builder/BuilderOsx.js

I have a limited knowledge of macOS packages, but I assume the binary will still work with a modified CFBundleIdentifier.

Feel free to create a pull request, otherwise I will try and take a look at this soon.
